### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 1, Ours: 2

### ISSUE THREAD

**Issue by triasity** [prudhvitella/terraform-provider-infoblox#5] opened 2016-06-23 23:58 UTC
I'm currently using Terraform v0.6.15. What terraform version is this plugin compatible with? Are there any releases that are compatible with newer versions of terraform?

**Comment by gbolo** [comment] 2016-07-05 18:18
+1

**Comment by prudhvitella** [comment] 2016-07-05 21:51
It is compatible with v0.6.x releases. This plugin needs to be updated once 0.7.X is released due to plugin-protocol changes.

**Comment by gbolo** [comment] 2016-07-05 22:12
Was it compiled against the v0.6.x release of terraform? This is how I am testing:
```
root@ansible ~ $ terraform version
Terraform v0.6.16

root@ansible ~ $ wget https://github.com/prudhvitella/terraform-provider-infoblox/releases/download/pre-release/linux_amd64_terraform-provider-infoblox -O /usr/local/bin/terraform-provider-infoblox

root@ansible ~ $ chmod +x /usr/local/bin/terraform-provider-infoblox

root@ansible ~/ansible-dev/terraform $ cat test.tf
# Configure the Infoblox provider
provider "infoblox" {
    username = "test"
    password = "test"
    host  = "test.local"
    sslverify = false
}
resource "infoblox_record" "foobar" {
    value = "192.168.0.10"
    name = "terraform"
    domain = "mydomain.com"
    type = "A"
    ttl = 3600
}

root@ansible ~/ansible-dev/terraform $ terraform plan
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 1, Ours: 2
```

prudhvitella, can you verify these steps on a VM? terraform binaries were taken from official source:
https://releases.hashicorp.com/terraform/0.6.16/terraform_0.6.16_linux_amd64.zip

**Comment by prudhvitella** [comment] 2016-07-06 00:02
I'll verify and let you know.

**Comment by prudhvitella** [comment] 2016-07-08 22:51
@gbolo I was able to reproduce the issue. I added vendoring and built the plugin against v0.6.16 tag. The latest build should work now.

**Comment by jasminSPC** [comment] 2016-07-11 13:57
I am also developing a third-party plugin and I'm having the same issue.
```
$ terraform version
Terraform v0.6.16

$ terraform plan 
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 1, Ours: 2
```

Is it possible to make my plugin work with the latest version of terraform?

**Comment by prudhvitella** [comment] 2016-07-11 20:36
It is possible. Compile against v0.6.16 by using tools like [govendor](https://github.com/kardianos/govendor) or [govend](https://github.com/govend/govend)

**Comment by triasity** [comment] 2016-07-16 19:23
@prudhvitella I'm no longer getting the incompatible api version error. However, I keep receiving a new error regarding an unknown object type. 

Here is my terraform code:
```
provider "infoblox" {
    username = "${var.infoblox_username}"
    password = "${var.infoblox_password}"
    host = "https://10.1.101.10/wapi/v1.2/"
    sslverify = false
}

resource "infoblox_record" "chef" {
    value = "${aws_instance.test.private_ip}"
    name = "test"
    domain = "mydomain.com"
    type = "A"
    ttl = 3600
}
```

Here is the error:
```
infoblox_record.chef: Creating...
  domain: "" => "mydomain.com"
  name:   "" => "test"
  ttl:    "" => "3600"
  type:   "" => "A"
  value:  "" => "10.20.130.7"
Error applying plan:

1 error(s) occurred:

* infoblox_record.chef: Failed to create Infblox Record: Error AdmConProtoError: Unknown object type () - Client.Ibap.Proto - Unknown object type ()
```

**Comment by prudhvitella** [comment] 2016-08-19 23:06
Closing since it works

**Closed by prudhvitella** 2016-08-19 23:06 UTC

**Comment by zenvdeluca** [comment] 2017-06-29 06:37
Hi @prudhvitella 

i am getting same error with Terraform v0.9.8
* provider.infoblox: Incompatible API version with plugin. Plugin version: 2, Ours: 4

**Comment by zenvdeluca** [comment] 2017-06-29 18:49
n/m, I rebuilt and seems to work
